- hosts: all
  become: yes
  remote_user: vagrant

  tasks:
  - name: Actualizar sistema
    command: apt-get update

  - name: Instalar Git
    command: apt-get install -y git

  - name: Instalar pip
    command: apt-get install -y python3-pip

  - name: Clonar GitHub
    git: repo=https://github.com/vaderrama/Proyecto-IV.git  dest=Proyecto-IV/ force=yes

  - name: Instalar requirements
    command: pip3 install -r Proyecto-IV/requirements.txt
